### ISSUE TITLE
Add raffle feature

### ISSUE THREAD

**Issue by jarrodknox** [MHCommunity/mousehunt-improved#225]
Is it possible to get a button that returns all raffle draw entries? So when going to inbox and daily draw, there are a bunch of people that sent you raffles, and you click each one individually to return it. Would be great to just click once and it returns all.

**Comment by jarrodknox** [comment]
Seems the raffle return will only work on unread messages.

I had a whole list of received raffles, and of those 5 were sitting as unread.

Upon clicking return raffles it quickly went through the list of 5 and stopped, returning to the send raffles button

I clicked the button again and it changed to sending and click to stop sending, but it stayed there and did not seem to be going down the list.

I closed the inbox, and opened again and sent manually and it allowed me to send to those that were read originally, but it had successfully sent to the 5 that were unread.

<img width="528" alt="image" src="https://github.com/MHCommunity/mousehunt-improved/assets/88068508/09b4ad7f-ebf8-473b-a811-aaa057e9436c">

**Comment by bradp** [comment]
When it goes through and returns raffles, it saves which ones it sends so that it can skip over those next time. But if it's not a ballot that it has returned & saved and it encounters a 'You have already entered <person>', then it will stop and not proceed.

The idea is that if we hit a point where we're trying to send ballots that we don't know about and they're failing, it's just better to err on the side of caution and not go into a loop of attempting to send them.

**Comment by jarrodknox** [comment]
Ah ok, thats fair

Today worked perfectly with both the ones showing as read and unread. Even though I am not reading these it seems they seem to mark some as if they were. I will try take more notice of this too, as its a bit weird

**Comment by bradp** [comment]
Going to close this, feel free to reopen if there's any other weirdness. Thanks!
