### ISSUE TITLE
Return the link to the Mousehunt Community page please!

### ISSUE THREAD

**Issue by solamon77** [MHCommunity/mousehunt-improved#318]
A small request... before installing Mousehunt Improved there was a tab in the top bar called Community that contained a link called Fan Page that took you to the Mousehunt Facebook page. Would it be possible to add that back? Maybe under the new Help tab? They give away gifts on that page all the time and that link made it very convenient to go get those gifts. Thanks!
![Screenshot (6)](https://github.com/MHCommunity/mousehunt-improved/assets/21700904/45d8fd84-0624-4b1f-9f1a-a5dc9afded78)

**Comment by bradp** [comment]
The Location Dashboard module hides it to make space in the top menu, otherwise it's a bit too cluttered.

But it's very easy to get it back! You can add the following to the **[Custom Styles](https://www.mousehuntgame.com/preferences.php?tab=mousehunt-improved-settings#mousehunt-improved-settings-advanced-override-styles)** field under Advanced Settings

```css
.mousehuntHeaderView-gameTabs .community {
    display: block;
}
```

I've also added this to the Custom CSS [wiki page](https://github.com/MHCommunity/mousehunt-improved/wiki/Custom-CSS) in case others want this as well.

Hope that helps! If you need further help with it, feel free to re-open this issue.
